@baseUrl = http://localhost:3000

### Read all categories sorted by title (ascending)
GET {{baseUrl}}/categories/?order=+title

### Read all categories sorted by title (descending)
GET {{baseUrl}}/categories/?order=-title

### Create category without the admin right
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "title":"Test1"
}
### Create category without the admin right
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "title":"Zab"
}
### Create category without the admin right
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "title":"Brrrrrrr"
}

### Delete a category by title
DELETE {{baseUrl}}/categories/Br
Content-Type: application/json

### Delete First catagory
DELETE {{baseUrl}}/categories/
Content-Type: application/json


### Create a categorie with user token
#### First, Login as a user 
##### Login the user and get the response in a request variable named 'user'
# @name user

POST {{baseUrl}}/auths/login
Content-type: application/json

{
    "username": "Alic",
    "password": "alice123"
}





### Add category as a user without rights
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: {{user.response.body.token}}

{
    "title": "Par User = Erreur"
}


##### Login the user and get the response in a request variable named 'user'
# @name admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username": "admin", 
    "password": "admin"
}



