### Read all topics
@baseUrl = http://localhost:3000
GET {{baseUrl}}/categories

### Read all topics sorted by title (ascending)
GET {{baseUrl}}/categories/?order=+title

### Read all topics sorted by title (descending)
GET {{baseUrl}}/categories/?order=-title

### Create topic without the admin right
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "title":"Test1"
}
### Create topic without the admin right
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "title":"Zab"
}
### Create topic without the admin right
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "title":"Br"
}

### Delete a category
DELETE {{baseUrl}}/categories/2
Content-Type: application/json

### Delete First catagory
DELETE {{baseUrl}}/categories/
Content-Type: application/json