@baseUrl = http://localhost:3000

### Read all categories sorted by title (ascending)
GET {{baseUrl}}/categories/?order=+title

### Create a categorie with user token
#### First, Login as a user 
##### Login the user and get the response in a request variable named 'user'
# @name user

POST {{baseUrl}}/auths/login
Content-type: application/json

{
    "username": "Marwan",
    "password": "alice123"
}

### Add category as a user without authorization
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "title": "Jeux vidéos"
}
### Add category as a user without rights
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: {{user.response.body.token}}

{
    "title": "Jeux vidéos"
}


##### Login the user and get the response in a request variable named 'user'
# @name admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username": "admin", 
    "password": "admin"
}

### Create category without the admin right
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: {{admin.response.body.token}}

{
    "title":"Sports"
}

### Create another category without the admin right
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: {{admin.response.body.token}}

{
    "title":"Musique"
}
### Create another category without the admin right
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: {{admin.response.body.token}}

{
    "title":"Loisir"
}

### Delete a category by id
DELETE {{baseUrl}}/categories/7
Content-Type: application/json
Authorization: {{admin.response.body.token}}

### Delete a category by id unexistant
DELETE {{baseUrl}}/categories/666
Content-Type: application/json
Authorization: {{admin.response.body.token}}




